# SPDX-License-Identifier: GPL-2.0-only
CFLAGS += -iquote../../../../include/uapi -Wall
peeksiginfo: peeksiginfo.c

all: peeksiginfo

clean:
	rm -f peeksiginfo

TEST_PROGS := peeksiginfo

include ../lib.mk
