# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2016 Imagination Technologies
# Author: Paul Burton <paul.burton@imgtec.com>
#

obj-y += init.o
obj-y += irq.o
obj-y += proc.o

obj-$(CONFIG_VIRT_BOARD_RANCHU)	+= board-ranchu.o
